name: Deploy peers to the route servers
on:
  push:
    branches:
      - 'master'
jobs:
  refresh-repo:
    runs-on: self-hosted
    steps:
      - run: 'git -C /opt/ixp/peers pull'
      - run: 'cp /opt/ixp/peers/clients.yml /etc/arouteserver/clients.yml'

